print('===========Arithmetic,Relational & Logical Operations========' )
b=int(input('Enter the number 1 To 5:'))
a=int(input('Enter the number 6 TO 10:'))

print('===============================================')
print('                   RESULTS                     ')
print('===============================================')
print('Arithmetic Operations:')
print('Addition         :',a+b)
print('Substraction     :',a-b)
print('Multiplication   :',a*b)
print('Division         :',a/b)
print('Floor Division   :',a//b)
print('Modulus          :',a%b)
print('Exponentiation   :',a**b)

print("\nRelational Operations:")
print("a == b   :", a == b) 
print("a != b   :", a != b)
print("a > b    :", a > b) 
print("a < b    :", a < b)
print("a >= b   :", a >= b)
print("a <= b   :", a <= b)

print("\nLogical Operations:")
print("(a > 5) and (b < 10) :", (a > 5) and (b < 10)) 
print("(a < 5) or (b < 10)  :", (a < 5) or (b < 10)) 
print("not(a > b)           :", not(a > b))