print('====================STRING OPERATIONS===============')
X=input('ENTER THE STRING :')

print('===============================================')
print('                   RESULTS                     ')
print('===============================================')
print('Entered String           :',X)
print('Printing 5 characters    :',X[0:5])
print('Reversed String          :',X[::-1])
print('Length of String         :',len(X))
print('Printing 5 characters    :',X[0:5])
print('"Hello" in String        :' ,"hello" in X)
print('"Not Hello" in String    :' ,"hello" not in X)
print('"Hello" in String        :' ,"hello" in X)
print("\n--- Built-in String Functions ---")
print("Uppercase            :", X.upper())
print("Lowercase            :", X.lower())
print("Title Case           :", X.title())
print("Count of 'a'         :", X.count('a'))
print("Replace 'a' with '@' :", X.replace('a', '@'))
print("Starts with 'H'      :", X.startswith('H'))
print("Ends with '!'        :", X.endswith('!'))
print("Is Alphabetic        :", X.isalpha())
print("Is Digit             :", X.isdigit())
print("Split String         :", X.split())