print('==================List Operations===============')
x=[5,10,15,20,25,30]
y=[6,7,8,9,10]
print('LIST                         :',x)
print("First element                :", x[0])
print("Third element                :", x[2])
print("Last element                 :", x[-1])
print("First three elements         :", x[:3])
print("Elements from index 2 to 4   :", x[2:5])
print("Last three elements          :", x[-3:])
print("Reversed list                :", x[::-1])
x.append(70)
print('Updated List                 :',x)
print('Count of 10                  :',x.count(10))
x.insert(1,35)
print('Inserted 35 in List          :',x)
x.remove(35)
print('Removed 35 frm List          :',x)
square=[i**2 for i in x]
print('Squares of List              :',square)
print('Index of 15                  :',x.index(15))
print('POP the 20                   :',x.pop(3))
x.extend(y)
print('Extend                       :',x)
x.reverse()
print("Reversed list Using function :",x )