print('=================DEMONSTRATING IF STATEMENT====================')
print('check the number is greater than 10')
x=int(input('enter the number:'))
if x>10:
   print('entered number is Greater than 10')
print('=================DEMONSTRATING IF-ELSE STATEMENT====================')
y=input('Check the "h" is present :')
if "h" in y:
    print('H is present in the string.')
else:
    print('H is not present in the string.')
print('=================DEMONSTRATING IF-ELIF-ELSE STATEMENT====================')
z=input('Check the "h" or "a" is present :')
if 'h' in z:
    print('H is present in the string.')
elif 'a' in z:
    print('A is present in the string.')
else :
 print(' H & A is not present in the string')
